name       : sunshine
version    : 0.10.1
release    : 4
source     :
    - git|https://github.com/loki-47-6F-64/sunshine.git : 7a920da06d1417828674842f44b919b75d70d3fe
license    : GPL-3.0-only
component  : network.web
homepage   : https://github.com/loki-47-6F-64/sunshine
summary    : Gamestream host for Moonlight
description: |
    Open source implementation of NVIDIA's GameStream, as used by the NVIDIA Shield. It can be used with any Moonlight client.
    Sunshine gets configured through a web UI.
builddeps  :
    - pkgconfig(libavformat)
    - pkgconfig(libevdev)
    - pkgconfig(icu-i18n)
    - pkgconfig(libpulse)
    - pkgconfig(opus)
    - pkgconfig(xfixes)
    - pkgconfig(xrandr)
    - libboost-devel
setup      : |
    mkdir build && cd build
    %cmake .. -D SUNSHINE_ASSETS_DIR=/usr/share/sunshine -D SUNSHINE_CONFIG_DIR=/etc/sunshine -D SUNSHINE_DEFAULT_DIR=/usr/share/defaults/etc/sunshine -D SUNSHINE_EXECUTABLE_PATH=/usr/bin/sunshine
build      : |
    %make -C build
install    : |
    install -Dm00755 $workdir/build/sunshine $installdir/usr/bin/sunshine

    mkdir -p $installdir/usr/share/sunshine/shaders
    mkdir -p $installdir/usr/share/sunshine/web
    cp -Rv $workdir/assets/shaders/* $installdir/usr/share/sunshine/shaders
    cp -Rv $workdir/assets/web/* $installdir/usr/share/sunshine/web
    install -Dm00644 $workdir/assets/box.png $installdir/usr/share/sunshine/box.png

    install -dm00777 $installdir/etc/sunshine
    install -Dm00666 $workdir/assets/apps_linux.json $installdir/usr/share/defaults/etc/sunshine/apps_linux.json
    install -Dm00666 $workdir/assets/sunshine.conf $installdir/usr/share/defaults/etc/sunshine/sunshine.conf

    install -Dm00644 $workdir/build/sunshine.service $installdir/%libdir%/systemd/user/sunshine.service
    install -Dm00644 $pkgfiles/udev.rules $installdir/%libdir%/udev/rules.d/85-sunshine.rules
