name       : sunshine
version    : 0.15.0
release    : 5
source     :
    - git|https://github.com/LizardByte/Sunshine.git : e1b112cafde0e1c668c7ae0d0f4592f5cdd0550a
license    : GPL-3.0-only
component  : network.web
homepage   : https://github.com/LizardByte/Sunshine
summary    : Gamestream host for Moonlight
description: |
    Open source implementation of NVIDIA's GameStream, as used by the NVIDIA Shield. It can be used with any Moonlight client.
    Sunshine gets configured through a web UI.
builddeps  :
    - pkgconfig(icu-i18n)
    - pkgconfig(libavformat)
    - pkgconfig(libcap)
    - pkgconfig(libdrm)
    - pkgconfig(libevdev)
    - pkgconfig(libpulse)
    - pkgconfig(opus)
    - pkgconfig(wayland-server)
    - pkgconfig(xfixes)
    - pkgconfig(xrandr)
    - libboost-devel
setup      : |
    mkdir build && cd build
    %cmake .. -D SUNSHINE_ASSETS_DIR=share/sunshine/assets
build      : |
    %make -C build
install    : |
    %make_install -C build
