name       : sunshine
version    : 0.16.0
release    : 7
source     :
    - git|https://github.com/LizardByte/Sunshine.git : 08d623ce44f77061a26de9dc50a2aef60f1b6158
license    : GPL-3.0-only
component  : network.web
homepage   : https://github.com/LizardByte/Sunshine
summary    : Gamestream host for Moonlight
description: |
    Open source implementation of NVIDIA's GameStream, as used by the NVIDIA Shield. It can be used with any Moonlight client.
    Sunshine gets configured through a web UI.
networking : true
builddeps  :
    - pkgconfig(icu-i18n)
    - pkgconfig(libavformat)
    - pkgconfig(libcap)
    - pkgconfig(libcurl)
    - pkgconfig(libdrm)
    - pkgconfig(libevdev)
    - pkgconfig(libpulse)
    - pkgconfig(libva)
    - pkgconfig(numa)
    - pkgconfig(opus)
    - pkgconfig(vdpau)
    - pkgconfig(xfixes)
    - pkgconfig(xrandr)
    - libboost-devel
    - nodejs
setup      : |
    pushd src_assets/common/assets/web
        npm install
    popd
    mkdir build && cd build
    %cmake -D SUNSHINE_ASSETS_DIR=share/sunshine/assets ..
build      : |
    %make -C build
install    : |
    %make_install -C build
