name       : sunshine
version    : 0.8.0
release    : 1
source     :
    - git|https://github.com/loki-47-6F-64/sunshine.git : ae04c4afbbc44e1b6e15fcb38e9afdd6473b5005
license    : GPL-3.0-only
component  : network.web
homepage   : https://github.com/loki-47-6F-64/sunshine
summary    : Gamestream host for Moonlight
description: |
    Open source implementation of NVIDIA's GameStream, as used by the NVIDIA Shield. It can be used with any Moonlight client.
    Sunshine gets configured through a web UI.
builddeps  :
   - pkgconfig(libavformat)
   - pkgconfig(libevdev)
   - pkgconfig(libpulse)
   - pkgconfig(opus)
   - pkgconfig(xfixes)
   - pkgconfig(xrandr)
   - pkgconfig(xtst)
   - libboost-devel
setup      : |
    mkdir build && cd build
    %cmake .. -D SUNSHINE_ASSETS_DIR=/usr/share/sunshine
build      : |
    %make -C build
install    : |
    install -Dm00755 $workdir/build/sunshine $installdir/usr/bin/sunshine

    mkdir -p $installdir/usr/share/sunshine/shaders
    mkdir -p $installdir/usr/share/sunshine/web
    cp -Rv $workdir/assets/shaders/* $installdir/usr/share/sunshine/shaders
    cp -Rv $workdir/assets/web/* $installdir/usr/share/sunshine/web
    install -Dm00644 $workdir/assets/box.png $installdir/usr/share/sunshine/box.png

    install -Dm00666 $workdir/assets/apps_linux.json $installdir/usr/share/sunshine/apps_linux.json
    install -Dm00666 $workdir/assets/sunshine.conf $installdir/usr/share/sunshine/sunshine.conf

    install -Dm00644 $workdir/build/sunshine.service $installdir/%libdir%/systemd/user/sunshine.service
    install -Dm00644 $pkgfiles/udev.rules $installdir/%libdir%/udev/rules.d/85-sunshine.rules
